#en-tete 
name: Java CLI with mvnw - devops tp3

#declencheurs 
on: 
  push:
  pull_request:
  workflow_dispatch:
  
#variables globales SI il y en a

jobs: 
  unit-tests: 
    runs-on: ubuntu-latest
    steps: 
      - name: checkout-code
        uses: actions/checkout@v4
      - name: setup jdk 
        uses: actions/setup-java@v5
        with: 
          distribution: 'temurin'
          java-version: '21'
          #on github marketplace > setup java..
      - name: install mvnw 
        run: mvn -N wrapper:wrapper
      - name: build project
        run: ./mvnw clean package
      - name: run unit-tests 
        run: ./mvnw test

  check-image-build: 
    steps: 
      - name: test building the app 
      - run: docker build -t tp3-java:test .

  #faire les test de documentation dans le job de tests
  #faire les tests 



  doc-on-netlify:
    if: github.refs == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps: 
      - name: checkout-code
        uses: actions/checkout@v4
      - name: setup jdk 
        uses: actions/setup-java@v5
        with: 
          distribution: 'temurin'
          java-version: '21'
      - name: build-doc
        run: mvn javadoc:javadoc
      - name: install-node
        run: sudo apt update && sudo apt install nodejs npm
      - name: install-netlify
        run: npm install -g netlify-cli
      - name: deploy-doc-on-netlify
        run: netlify deploy --prod --dir=target/reports/apidocs
        env: 
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN}}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID}}
